name       : haskell-cryptonite
version    : 0.22
release    : 1
source     :
    - http://hackage.haskell.org/package/cryptonite-0.22/cryptonite-0.22.tar.gz : 4be312a42a12ccd2ca60272ef485664f242c7ed89fa1909ba36a54c5fb6ff5f0
license    : BSD-3-Clause
component  : programming.haskell
summary    : A repository of cryptographic primitives.
description: |
    A repository of cryptographic primitives.
builddeps  :
    - haskell-cabal-install
    - haskell-memory
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
