name       : haskell-cryptonite
version    : '0.25'
release    : 2
source     :
    - https://hackage.haskell.org/package/cryptonite-0.25/cryptonite-0.25.tar.gz : 89be1a18af8730a7bfe4d718d7d5f6ce858e9df93a411566d15bf992db5a3c8c
license    : BSD-3-Clause
component  : programming.haskell
summary    : A repository of cryptographic primitives.
description: |
    A repository of cryptographic primitives.
builddeps  :
    - haskell-cabal-install
    - haskell-memory
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
