name       : haskell-cryptonite
version    : '0.26'
release    : 3
source     :
    - https://hackage.haskell.org/package/cryptonite-0.26/cryptonite-0.26.tar.gz : c47390df555295fdb1fb8161c190e208f43b8d334b2da3e96f0c64b7fe07aedd
license    : BSD-3-Clause
component  : programming.haskell
summary    : A repository of cryptographic primitives.
description: |
    A repository of cryptographic primitives.
builddeps  :
    - haskell-cabal-install
    - haskell-memory-devel
rundeps    :
    - devel:
        - haskell-memory-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
